version: "2.4"


services:
    dlcv:
        image : dlcv
        container_name: dlcv


        runtime: nvidia

        user: 1000:1000 
        environment:
            - DISPLAY=$DISPLAY
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - "QT_X11_NO_MITSHM=1" 



        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ../:/DLCV

        