version: "2.4"


services:
    dlcv:
        image : dlcv
        container_name: dlcv
  

        runtime: nvidia

        user: 1000:1000 
        environment:
            - DISPLAY=$DISPLAY
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - "QT_X11_NO_MITSHM=1" 



        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ../:/home/deeplearn/DL4CV

            - unique-vol-name-here:/deeplearn/.vscode-server/extensions
            - unique-vol-name-here-insiders:/deeplearn/.vscode-server-insiders/extensions

volumes:
    unique-vol-name-here:
    unique-vol-name-here-insiders: